export const courses = [
  {
    id: 1,
    name: "Advanced Web Development",
    description: "Learn modern web development techniques and best practices",
    lectureCount: 24,
    source: "Bayut",
    tags: ["Web Development", "Frontend"],
  },
  {
    id: 2,
    name: "Data Science Fundamentals",
    description:
      "Explore data analysis, visualization, and machine learning concepts",
    lectureCount: 30,
    source: "Dubizzle",
    tags: [
      "Data Science",
      "Machine Learning",
      "Data Analysis",
      "Data Handling",
    ],
  },
  {
    id: 3,
    name: "Mobile App Development",
    description:
      "Build native and cross-platform mobile applications from scratch",
    lectureCount: 20,
    source: "BWC",
    tags: [
      "Mobile Development",
      "Cross-Platform",
      "App Development",
      "Frontend",
    ],
  },
  {
    id: 4,
    name: "Cybersecurity Essentials",
    description:
      "Understand key cybersecurity principles and practices to protect systems",
    lectureCount: 18,
    source: "Emaar",
    tags: [
      "Cybersecurity",
      "Security Principles",
      "System Protection",
      "Data Handling",
    ],
  },
  {
    id: 5,
    name: "Cloud Computing Mastery",
    description:
      "Dive into cloud infrastructure, deployment, and services management",
    lectureCount: 25,
    source: "Raheja",
    tags: ["Cloud Computing", "Cloud Infrastructure", "Deployment", "Services"],
  },
  {
    id: 6,
    name: "CRM Management",
    description:
      "Dive into CRM Management, customization, and services management",
    lectureCount: 25,
    source: "Raheja",
    tags: ["CRM", "Pipelines", "Services"],
  },
];

export const lessonsData = [
  {
    id: 1,
    sequence: 1,
    title: "Introduction to React Fundamentals",
    duration: "45 mins",
    type: "video",
    description:
      "Learn the core concepts of React and its component-based architecture",
    isLocked: false,
    completed: true,
  },
  {
    id: 2,
    sequence: 2,
    title: "State Management in React",
    duration: "55 mins",
    type: "video",
    description: "Deep dive into useState, useEffect and component lifecycle",
    isLocked: false,
    completed: true,
  },
  {
    id: 3,
    sequence: 3,
    title: "Props and Component Communication",
    duration: "40 mins",
    type: "video",
    description: "Understanding data flow between React components",
    isLocked: false,
    completed: false,
  },
  {
    id: 4,
    sequence: 4,
    title: "React Hooks in Detail",
    duration: "60 mins",
    type: "video",
    description: "Comprehensive guide to built-in React hooks",
    isLocked: false,
    completed: false,
  },
  {
    id: 5,
    sequence: 5,
    title: "Advanced State Management",
    duration: "50 mins",
    type: "video",
    description: "Context API, Redux, and other state management solutions",
    isLocked: true,
    completed: false,
  },
  {
    id: 6,
    sequence: 6,
    title: "React Router and Navigation",
    duration: "35 mins",
    type: "video",
    description: "Building multi-page applications with React Router",
    isLocked: true,
    completed: false,
  },
  {
    id: 7,
    sequence: 7,
    title: "Forms and User Input",
    duration: "45 mins",
    type: "video",
    description: "Handling forms, validation, and user input in React",
    isLocked: true,
    completed: false,
  },
  {
    id: 8,
    sequence: 8,
    title: "API Integration",
    duration: "55 mins",
    type: "video",
    description: "Working with REST APIs and handling async operations",
    isLocked: true,
    completed: false,
  },
  {
    id: 9,
    sequence: 9,
    title: "Performance Optimization",
    duration: "50 mins",
    type: "video",
    description: "Techniques to optimize React application performance",
    isLocked: true,
    completed: false,
  },
  {
    id: 10,
    sequence: 10,
    title: "Deployment and Best Practices",
    duration: "40 mins",
    type: "video",
    description: "Deploying React apps and following industry best practices",
    isLocked: true,
    completed: false,
  },
];
